# Generated by Django 6.0.5 on 2026-06-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0006_project_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'permissions': [('manage_project_users', 'Can manage project users')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
